SET FOREIGN_KEY_CHECKS=0;
INSERT INTO ADDRESS (STREET,ADDITIONALINFO,CITYINFO_ZIPCODE) VALUES ('SOMEWHERE','SOMETEXT',2800);
INSERT INTO INFOENTITY (EMAIL,ADDRESS_STREET) VALUES ('SOMEEMAIL@DK.DK',1);
INSERT INTO PERSON (FIRSTNAME,LASTNAME,ADDRESS_STREET,EMAIL) VALUES ('SOMEFIRST', 'SOMELAST',1,1);