SET FOREIGN_KEY_CHECKS=0;
INSERT INTO ADDRESS (STREET,ADDITIONALINFO,CITYINFO_ZIPCODE) VALUES ('SOMEWHERE','SOMETEXT','2800');
INSERT INTO ADDRESS (STREET,ADDITIONALINFO,CITYINFO_ZIPCODE) VALUES ('SOMEWHERE2','SOMETEXT2','0800');

INSERT INTO INFOENTITY (EMAIL,ADDRESS_STREET) VALUES ('SOMEEMAIL@DK.DK',1);
INSERT INTO INFOENTITY (EMAIL,ADDRESS_STREET) VALUES ('SOMEEMAIL2@DK.DK',2);

INSERT INTO PERSON (FIRSTNAME,LASTNAME,ADDRESS_STREET,EMAIL) VALUES ('SOMEFIRST', 'SOMELAST',1,1);
INSERT INTO PERSON (FIRSTNAME,LASTNAME,ADDRESS_STREET,EMAIL) VALUES ('SOMEFIRST2', 'SOMELAST2',2,2);

INSERT INTO COMPANY(CVR,DESCRIPTION,EMAIL,MARKETVALUE,NAME,PHONE,ADDRESS_STREET) VALUES('22446688','HELLO COMPANY1',1,1000.0,'COMPANY1','+4588888888','COMPANY ADDRESS');
INSERT INTO COMPANY(CVR,DESCRIPTION,EMAIL,MARKETVALUE,NAME,ADDRESS_STREET) VALUES('22334455','HELLO COMPANY2',2,2000.0,'COMPANY2','COMPANY ADDRESS2');